---
deployment:
  tasks:
    - export REPOPATH=/home2/x47491/starter/*
    - export SITEPATH=/home2/x47491/public_html/starter.xander.work/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH